---
name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/linters  # Points to custom linter rules (if any)
          VALIDATE_ALL_CODEBASE: true         # Validate entire codebase
          FILE_EXTENSIONS: |
            js
            ts
            py
            yml
          DISABLE_LINTERS: |
            markdown
            dockerfile
